import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "material-symbols";
import "../styles/index.scss";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";
import Content from "@/components/Content/content";
import { IconNeonCat } from "@/components/Icon/presetIcon";
import { MessageProvider } from "@/contexts/message/context";
import { MessageContainer } from "@/components/Message";
import { MessageInstanceInitializer } from "@/contexts/message/instance";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const routeList = ["home", "blog", "album", "contact"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased neu-light body-content`}
      >
        <MessageProvider>
          <MessageInstanceInitializer />
          <Navbar leftSlot={<IconNeonCat />} routeList={routeList} />
          <Content>{children}</Content>
          <Footer></Footer>
          <MessageContainer />
        </MessageProvider>
      </body>
    </html>
  );
}
