import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "material-symbols/outlined.css";
import "../styles/index.scss";
import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer/footer";
import Head from "next/head";
import { Toaster } from "@/components/ProMessage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const routeList = ["home", "blog", "album", "contact", "todo"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased neu-light body-content`}
      >
        <Toaster richColors visibleToasts={5} />
        <Navbar routeList={routeList} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
